export interface Faction {
  name: string;
  icon: string;
  color: string;
}

export interface Ship {
  name: string;
  fullName?: string;
  modifier?: string;
  icon: string;
  height: number;
  width: number;
  length: number;
  sideLeftOffset?: number;
  sideRightOffset?: number;
  displaySide?: boolean;
  displayTop?: boolean;
  displayFactionSize: number;
  displayIconSize: number;
  displaySideFactionSize?: number;
  displaySideIconSize?: number;
  displayTopFactionSize?: number;
  displayTopIconSize?: number;
  factions: string[];
}

interface Data {
  factions: Faction[];
  ships: Ship[];
}

export const data: Data = {
  "factions": [
    {
      "name": "Rebel Alliance",
      "icon": "!",
      "color": "#CD3E43"
    },
    {
      "name": "Galactic Empire",
      "icon": "@",
      "color": "#567086"
    },
    {
      "name": "Scum and Villainy",
      "icon": "#",
      "color": "#C26422"
    },
    {
      "name": "Resistance",
      "icon": "-",
      "color": "#E55B05"
    },
    {
      "name": "First Order",
      "icon": "+",
      "color": "#000000"
    },
    {
      "name": "Galactic Republic",
      "icon": "/",
      "color": "#651616"
    },
    {
      "name": "Seperatist Alliance",
      "icon": ".",
      "color": "#15155F"
    }
  ],
  "ships": [
    {
      "name": "Belbullab-22 Starfighter",
      "icon": "[",
      "height": 14,
      "width": 22,
      "length": 33,
      "sideLeftOffset": -7,
      "displayFactionSize": 5,
      "displayIconSize": 21,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 7,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 4,
      "factions": ["Seperatist Alliance"]
    },
    {
      "name": "Droid Tri-Fighter",
      "icon": "+",
      "height": 21,
      "width": 19,
      "length": 29,
      "sideLeftOffset": 0,
      "sideRightOffset": 2,
      "displayFactionSize": 5,
      "displayIconSize": 19,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 16,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 13,
      "factions": ["Seperatist Alliance"]
    },
    {
      "name": "HMP Droid Gunship",
      "icon": ".",
      "height": 13,
      "width": 43,
      "length": 55,
      "sideLeftOffset": -4.5,
      "displayFactionSize": 5,
      "displayIconSize": 46,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 7,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 5,
      "factions": ["Seperatist Alliance"]
    },
    {
      "name": "Hyena-Class Droid Bomber",
      "icon": "=",
      "height": 13,
      "width": 33,
      "length": 47,
      "sideLeftOffset": -8.5,
      "displayFactionSize": 5,
      "displayIconSize": 38,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 7,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 5,
      "factions": ["Seperatist Alliance"]
    },
    {
      "name": "Nantex-Class Starfighter",
      "icon": ";",
      "height": 10,
      "width": 20,
      "length": 42,
      "displayTop": false,
      "displaySide": false,
      "displayFactionSize": 5,
      "displayIconSize": 29,
      "factions": ["Seperatist Alliance"]
    },
    {
      "name": "Vulture-class Droid Fighter",
      "icon": "_",
      "height": 16,
      "width": 24,
      "length": 34,
      "sideLeftOffset": -7,
      "displayFactionSize": 5,
      "displayIconSize": 22,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 9,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 5,
      "factions": ["Seperatist Alliance"]
    },
    {
      "name": "TIE Interceptor",
      "icon": "I",
      "height": 25,
      "width": 32,
      "length": 40,
      "sideLeftOffset": 3,
      "displayFactionSize": 5,
      "displayIconSize": 28,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 16,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 15,
      "factions": ["Galactic Empire"]
    },
    {
      "name": "TIE/D Defender",
      "icon": "D",
      "height": 42,
      "width": 42,
      "length": 38,
      "sideLeftOffset": 10,
      "displayFactionSize": 5,
      "displayIconSize": 26,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 28,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 32,
      "factions": ["Galactic Empire"]
    },
    {
      "name": "RZ-1 A-Wing",
      "icon": "a",
      "height": 15,
      "width": 27,
      "length": 39,
      "displayFactionSize": 5,
      "displayIconSize": 27,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 6,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 4,
      "factions": ["Rebel Alliance"]
    },
    {
      "name": "A/SF-01 B-Wing",
      "modifier": "(Folding Wings)",
      "icon": "b",
      "height": 15,
      "width": 32,
      "length": 65,
      "sideLeftOffset": -3,
      "displayFactionSize": 5,
      "displayIconSize": 52,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 6,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 4,
      "factions": ["Rebel Alliance"]
    },
    {
      "name": "HWK-290 Light Freighter",
      "icon": "h",
      "height": 18,
      "width": 52,
      "length": 66,
      "sideLeftOffset": -8,
      "sideRightOffset": -3,
      "displayFactionSize": 5,
      "displayIconSize": 54,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 15,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 12,
      "factions": ["Rebel Alliance", "Scum and Villainy"]
    },
    {
      "name": "BTL-A4 Y-Wing",
      "modifier": "(2.0 Sculpt)",
      "icon": "y",
      "height": 17,
      "width": 33,
      "length": 63,
      "sideLeftOffset": -1,
      "displayFactionSize": 5,
      "displayIconSize": 47,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 9,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 7,
      "factions": ["Rebel Alliance", "Scum and Villainy"]
    },
    {
      "name": "TIE/rb Heavy",
      "icon": "J",
      "height": 42,
      "width": 62,
      "length": 56,
      "sideLeftOffset": 5,
      "sideRightOffset": 12,
      "displayFactionSize": 5,
      "displayIconSize": 47,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 40,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 35,
      "factions": ["Galactic Empire"]
    },
    {
      "name": "Aggressor Assault Fighter",
      "icon": "i",
      "height": 19,
      "width": 60,
      "length": 77,
      "sideLeftOffset": -6,
      "sideRightOffset": -4,
      "displayFactionSize": 5,
      "displayIconSize": 67,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 12,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 12,
      "factions": ["Scum and Villainy"]
    },
    {
      "name": "Kihraxz Fighter",
      "icon": "r",
      "height": 13,
      "width": 38,
      "length": 46,
      "sideLeftOffset": -3,
      "sideRightOffset": -1,
      "displayFactionSize": 5,
      "displayIconSize": 36,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 6,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 7,
      "factions": ["Scum and Villainy"]
    },
    {
      "name": "BTL-A4 Y-Wing",
      "modifier": "(1.0 Sculpt)",
      "icon": "y",
      "height": 14,
      "width": 32,
      "length": 63,
      "sideLeftOffset": -2,
      "sideRightOffset": -1,
      "displayFactionSize": 5,
      "displayIconSize": 47,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 9,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 7,
      "factions": ["Rebel Alliance", "Scum and Villainy"]
    },
    {
      "name": "M3-A Interceptor",
      "icon": "s",
      "height": 13,
      "width": 33,
      "length": 37,
      "sideLeftOffset": -5,
      "sideRightOffset": -2,
      "displayFactionSize": 5,
      "displayIconSize": 27,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 9,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 7,
      "factions": ["Scum and Villainy"]
    },
    {
      "name": "Scurrg H-6 Bomber",
      "icon": "H",
      "height": 21,
      "width": 52,
      "length": 77,
      "sideLeftOffset": -2,
      "sideRightOffset": 1,
      "displayFactionSize": 5,
      "displayIconSize": 40,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 16,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 12,
      "factions": ["Scum and Villainy"]
    },
    {
      "name": "StarViper-class Attack Platform",
      "icon": "v",
      "height": 27,
      "width": 39,
      "length": 69,
      "sideLeftOffset": -6,
      "sideRightOffset": -3,
      "displayFactionSize": 5,
      "displayIconSize": 58,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 19,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 17,
      "factions": ["Scum and Villainy"]
    },
    {
      "name": "Quadrijet Transfer Spacetug",
      "icon": "q",
      "height": 26,
      "width": 49,
      "length": 40,
      "sideLeftOffset": -4,
      "sideRightOffset": -2,
      "displayFactionSize": 5,
      "displayIconSize": 30,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 19,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 18,
      "factions": ["Scum and Villainy"]
    },
    {
      "name": "Mining Guild TIE Fighter",
      "icon": "C",
      "height": 28,
      "width": 36,
      "length": 43,
      "sideLeftOffset": -1,
      "sideRightOffset": 3,
      "displayFactionSize": 5,
      "displayIconSize": 33,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 23,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 17,
      "factions": ["Scum and Villainy"]
    },
    {
      "name": "M12-L Kimogila Fighter",
      "icon": "K",
      "height": 23,
      "width": 58,
      "length": 55,
      "sideLeftOffset": -1,
      "displayFactionSize": 5,
      "displayIconSize": 47,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 9,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 7,
      "factions": ["Scum and Villainy"]
    },
    {
      "name": "Fang Fighter",
      "modifier": "(1.0 Sculpt)",
      "icon": "M",
      "height": 15,
      "width": 44,
      "length": 46,
      "sideLeftOffset": 0,
      "sideRightOffset": 1,
      "displayFactionSize": 5,
      "displayIconSize": 37,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 9,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 7,
      "factions": ["Scum and Villainy"]
    },
    {
      "name": "G-1A Starfighter",
      "icon": "n",
      "height": 35,
      "width": 44,
      "length": 68,
      "sideLeftOffset": 6,
      "sideRightOffset": 9,
      "displayFactionSize": 5,
      "displayIconSize": 57,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 29,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 26,
      "factions": ["Scum and Villainy"]
    },
    {
      "name": "Z-95-AF4 Headhunter",
      "icon": "z",
      "height": 16,
      "width": 35,
      "length": 46,
      "sideLeftOffset": -5,
      "displayFactionSize": 5,
      "displayIconSize": 37,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 9,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 7,
      "factions": ["Rebel Alliance", "Scum and Villainy"]
    },
    {
      "name": "TIE Advanced x1",
      "icon": "A",
      "height": 21,
      "width": 34,
      "length": 32,
      "sideLeftOffset": 0,
      "sideRightOffset": 3,
      "displayFactionSize": 5,
      "displayIconSize": 23,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 18,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 12,
      "factions": ["Galactic Empire"]
    },
    {
      "name": "TIE Advanced v1",
      "icon": "R",
      "height": 19,
      "width": 34,
      "length": 31,
      "sideLeftOffset": 1,
      "displayFactionSize": 5,
      "displayIconSize": 20,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 11,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 10,
      "factions": ["Galactic Empire"]
    },
    {
      "name": "TIE/sk Striker",
      "icon": "T",
      "height": 18,
      "width": 38,
      "length": 64,
      "sideLeftOffset": 0,
      "sideRightOffset": 2,
      "displayFactionSize": 5,
      "displayIconSize": 26,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 12,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 10,
      "factions": ["Galactic Empire"]
    },
    {
      "name": "TIE/ag Aggressor",
      "icon": "`",
      "height": 24,
      "width": 32,
      "length": 35,
      "sideLeftOffset": 2,
      "displayFactionSize": 5,
      "displayIconSize": 25,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 16,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 15,
      "factions": ["Galactic Empire"]
    },
    {
      "name": "TIE/ph Phantom",
      "icon": "P",
      "height": 25,
      "width": 30,
      "length": 43,
      "sideLeftOffset": 1,
      "sideRightOffset": 5,
      "displayFactionSize": 5,
      "displayIconSize": 26,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 22,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 12,
      "factions": ["Galactic Empire"]
    },
    {
      "name": "TIE/ln Fighter",
      "icon": "F",
      "height": 34,
      "width": 36,
      "length": 44,
      "sideLeftOffset": 8,
      "sideRightOffset": 10,
      "displayFactionSize": 5,
      "displayIconSize": 26,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 28,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 22,
      "factions": ["Galactic Empire", "Rebel Alliance"]
    },
    {
      "name": "TIE/sa Bomber",
      "icon": "B",
      "height": 24,
      "width": 45,
      "length": 40,
      "sideLeftOffset": 3,
      "displayFactionSize": 5,
      "displayIconSize": 26,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 16,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 16,
      "factions": ["Galactic Empire"]
    },
    {
      "name": "TIE/ca Punisher",
      "icon": "N",
      "height": 30,
      "width": 56,
      "length": 47,
      "sideLeftOffset": 3,
      "sideRightOffset": 10,
      "displayFactionSize": 5,
      "displayIconSize": 26,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 28,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 22,
      "factions": ["Galactic Empire"]
    },
    {
      "name": "TIE Reaper",
      "icon": "V",
      "height": 22,
      "width": 56,
      "length": 90,
      "sideLeftOffset": 5,
      "displayFactionSize": 5,
      "displayIconSize": 76,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 10,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 12,
      "factions": ["Galactic Empire"]
    },
    {
      "name": "Alpha-class Star Wing",
      "icon": "&",
      "height": 34,
      "width": 36,
      "length": 65,
      "sideLeftOffset": 3,
      "sideRightOffset": 6,
      "displayFactionSize": 5,
      "displayIconSize": 26,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 28,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 32,
      "factions": ["Galactic Empire"]
    },
    {
      "name": "A/SF-01 B-Wing",
      "modifier": "(Fixed Wings)",
      "icon": "b",
      "height": 32,
      "width": 38,
      "length": 58,
      "sideLeftOffset": 5,
      "sideRightOffset": 9,
      "displayFactionSize": 5,
      "displayIconSize": 52,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 28,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 24,
      "factions": ["Rebel Alliance"]
    },
    {
      "name": "T-65 X-Wing",
      "modifier": "(Fixed Wings)",
      "icon": "x",
      "height": 18,
      "width": 41,
      "length": 49,
      "sideLeftOffset": 0,
      "sideRightOffset": 4,
      "displayFactionSize": 5,
      "displayIconSize": 40,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 14,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 4,
      "factions": ["Rebel Alliance"]
    },
    {
      "name": "T-65 X-Wing",
      "modifier": "(Folding Wings)",
      "icon": "x",
      "height": 14,
      "width": 40,
      "length": 49,
      "sideLeftOffset": 0,
      "sideRightOffset": 0,
      "displayFactionSize": 5,
      "displayIconSize": 40,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 6,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 4,
      "factions": ["Rebel Alliance"]
    },
    {
      "name": "ARC-170 Starfighter",
      "icon": "c",
      "height": 21,
      "width": 54,
      "length": 83,
      "sideLeftOffset": -3,
      "sideRightOffset": 1,
      "displayFactionSize": 5,
      "displayIconSize": 52,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 18,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 13,
      "factions": ["Rebel Alliance", "Galactic Republic"]
    },
    {
      "name": "Attack Shuttle",
      "icon": "g",
      "height": 18,
      "width": 29,
      "length": 46,
      "sideLeftOffset": -1,
      "sideRightOffset": 1,
      "displayFactionSize": 5,
      "displayIconSize": 37,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 13,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 10,
      "factions": ["Rebel Alliance"]
    },
    {
      "name": "Auzituck Gunship",
      "icon": "@",
      "height": 25,
      "width": 32,
      "length": 57,
      "sideLeftOffset": 2,
      "sideRightOffset": 4,
      "displayFactionSize": 5,
      "displayIconSize": 37,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 20,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 17,
      "factions": ["Rebel Alliance"]
    },
    {
      "name": "UT-60D U-Wing",
      "icon": "u",
      "height": 23,
      "width": 35,
      "length": 91,
      "sideLeftOffset": 3,
      "displayFactionSize": 5,
      "displayIconSize": 42,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 16,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 14,
      "factions": ["Rebel Alliance"]
    },
    {
      "name": "Sheathipede-class Shuttle",
      "icon": "%",
      "height": 20,
      "width": 24,
      "length": 43,
      "sideLeftOffset": -4,
      "sideRightOffset": -4,
      "displayFactionSize": 5,
      "displayIconSize": 31,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 10,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 4,
      "factions": ["Rebel Alliance", "Seperatist Alliance"]
    },
    {
      "name": "TIE/FO Fighter",
      "icon": "O",
      "height": 33,
      "width": 35,
      "length": 39,
      "sideLeftOffset": 8,
      "displayFactionSize": 5,
      "displayIconSize": 28,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 26,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 22,
      "factions": ["First Order"]
    },
    {
      "name": "TIE/SF Fighter",
      "icon": "S",
      "height": 33,
      "width": 35,
      "length": 39,
      "sideLeftOffset": 8,
      "displayFactionSize": 5,
      "displayIconSize": 29,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 26,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 24,
      "factions": ["First Order"]
    },
    {
      "name": "TIE/vn Silencer",
      "icon": "$",
      "height": 24,
      "width": 43,
      "length": 80,
      "sideLeftOffset": 3,
      "displayFactionSize": 5,
      "displayIconSize": 58,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 16,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 16,
      "factions": ["First Order"]
    },
    {
      "name": "TIE/Ba Interceptor",
      "icon": "j",
      "height": 26,
      "width": 34,
      "length": 41,
      "sideLeftOffset": 0,
      "sideRightOffset": 4,
      "displayFactionSize": 5,
      "displayIconSize": 32,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 22,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 18,
      "factions": ["First Order"]
    },
    {
      "name": "Xi-class Light Shuttle",
      "icon": "Q",
      "height": 45,
      "width": 85,
      "length": 72,
      "sideLeftOffset": -3,
      "displayFactionSize": 5,
      "displayIconSize": 52,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 6,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 4,
      "factions": ["First Order"]
    },
    {
      "name": "Delta-7 Aethersprite",
      "icon": "\\",
      "height": 16,
      "width": 29,
      "length": 39,
      "sideLeftOffset": -4,
      "displayFactionSize": 5,
      "displayIconSize": 30,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 9,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 8,
      "factions": ["Galactic Republic"]
    },
    {
      "name": "Naboo Royal N-1 Starfighter",
      "icon": "<",
      "height": 14,
      "width": 30,
      "length": 53,
      "sideLeftOffset": -10,
      "sideRightOffset": -8,
      "displayFactionSize": 5,
      "displayIconSize": 38,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 8,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 4,
      "factions": ["Galactic Republic"]
    },
    {
      "name": "Syliure-class Hyperspace Ring",
      "icon": "*",
      "height": 22,
      "width": 38,
      "length": 43,
      "sideLeftOffset": -7,
      "sideRightOffset": -5,
      "displayFactionSize": 5,
      "displayIconSize": 34,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 16,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 14,
      "factions": ["Galactic Republic"]
    },
    {
      "name": "Eta-2 Actis",
      "modifier": "in Syliure-class Hyperspace Ring",
      "icon": "-*",
      "height": 27,
      "width": 38,
      "length": 43,
      "sideLeftOffset": 0,
      "sideRightOffset": 2,
      "displayFactionSize": 5,
      "displayIconSize": 21,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 16,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 19,
      "factions": ["Galactic Republic"]
    },
    {
      "name": "Eta-2 Actis",
      "icon": "-",
      "height": 15,
      "width": 24,
      "length": 27,
      "sideLeftOffset": 0,
      "displayFactionSize": 5,
      "displayIconSize": 18,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 8,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 7,
      "factions": ["Galactic Republic"]
    },
    {
      "name": "V-19 Torrent",
      "icon": "^",
      "height": 27,
      "width": 32,
      "length": 58,
      "sideLeftOffset": 6,
      "displayFactionSize": 5,
      "displayIconSize": 48,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 16,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 18,
      "factions": ["Galactic Republic"]
    },
    {
      "name": "BTL-B Y-Wing",
      "icon": ":",
      "height": 16,
      "width": 34,
      "length": 72,
      "sideLeftOffset": 0,
      "displayFactionSize": 5,
      "displayIconSize": 52,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 6,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 4,
      "factions": ["Galactic Republic"]
    },
    {
      "name": "LAAT/i Gunship",
      "icon": "/",
      "height": 30,
      "width": 60,
      "length": 69,
      "sideLeftOffset": 6,
      "displayFactionSize": 5,
      "displayIconSize": 58,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 20,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 22,
      "factions": ["Galactic Republic"]
    },
    {
      "name": "Fireball",
      "icon": "0",
      "height": 16,
      "width": 50,
      "length": 49,
      "sideLeftOffset": 3,
      "displayFactionSize": 5,
      "displayIconSize": 38,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 6,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 7,
      "factions": ["Resistance"]
    },
    {
      "name": "T-70 X-Wing",
      "modifier": "(Fixed Wings)",
      "icon": "w",
      "height": 17,
      "width": 44,
      "length": 48,
      "sideLeftOffset": 0,
      "sideRightOffset": 2,
      "displayFactionSize": 5,
      "displayIconSize": 37,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 10,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 7,
      "factions": ["Resistance"]
    },
    {
      "name": "T-70 X-Wing",
      "modifier": "(Folding Wings)",
      "icon": "w",
      "height": 15,
      "width": 44,
      "length": 48,
      "sideLeftOffset": 0,
      "sideRightOffset": 1,
      "displayFactionSize": 5,
      "displayIconSize": 37,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 8,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 4,
      "factions": ["Resistance"]
    },
    {
      "name": "RZ-2 A-Wing",
      "icon": "E",
      "height": 16,
      "width": 23,
      "length": 38,
      "sideLeftOffset": 0,
      "sideRightOffset": 2,
      "displayFactionSize": 5,
      "displayIconSize": 28,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 9,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 8,
      "factions": ["Resistance"]
    },
    {
      "name": "Resistance Transport",
      "icon": ">",
      "height": 23,
      "width": 37,
      "length": 68,
      "sideLeftOffset": -3,
      "sideRightOffset": 2,
      "displayFactionSize": 5,
      "displayIconSize": 38,
      "displaySideFactionSize": 4,
      "displaySideIconSize": 20,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 12,
      "factions": ["Resistance"]
    },
    {
      "name": "Resistance Transport Pod",
      "icon": "?",
      "height": 14,
      "width": 21,
      "length": 23,
      "displaySide": false,
      "displayFactionSize": 4,
      "displayIconSize": 12,
      "displaySideFactionSize": 2,
      "displaySideIconSize": 20,
      "displayTopFactionSize": 4,
      "displayTopIconSize": 0,
      "factions": ["Resistance"]
    }
  ]
}
