export enum Factions {
  REBEL_ALLIANCE = "Rebel Alliance",
  GALACTIC_EMPIRE = "Galactic Empire",
  SCUM_AND_VILLAINY = "Scum and Villainy",
  RESISTANCE = "Resistance",
  FIRST_ORDER = "First Order",
  GALACTIC_REPUBLIC = "Galactic Republic",
  SEPARATIST_ALLIANCE = "Separatist Alliance"
}

export interface Panel {
  factionIconSize: number;
  shipIconSize: number;
  leftOffset?: number;
  rightOffset?: number;
}

export interface Ship {
  name: string;
  icon: string;
  factions: string[];
  fullName?: string;
  modifier?: string;

  dimensions: {
    size: ShipSizes;
    height: number;
    width: number;
    length: number;
  }

  panels: {
    primary: Panel;
    sides?: Panel;
    top?: Panel;
  }
}

const panels = {
  panels: {
  primary: {
    factionIconSize: 666,
    shipIconSize: 666
  },
  sides: {
    factionIconSize: 666,
    shipIconSize: 666,
    leftOffset: 666,
    rightOffset: 666
  },
  top: {
    factionIconSize: 666,
    shipIconSize: 666
  }
}
}

export interface Faction {
  name: Factions;
  icon: string;
  color: string;
}

export const factions: Faction[] = [
  {
    name: Factions.REBEL_ALLIANCE,
    icon: "!",
    color: "#CD3E43",
  },
  {
    name: Factions.GALACTIC_EMPIRE,
    icon: "@",
    color: "#567086",
  },
  {
    name: Factions.SCUM_AND_VILLAINY,
    icon: "#",
    color: "#C26422",
  },
  {
    name: Factions.RESISTANCE,
    icon: "-",
    color: "#E55B05",
  },
  {
    name: Factions.FIRST_ORDER,
    icon: "+",
    color: "#000000",
  },
  {
    name: Factions.GALACTIC_EMPIRE,
    icon: "/",
    color: "#651616",
  },
  {
    name: Factions.SEPARATIST_ALLIANCE,
    icon: ".",
    color: "#15155F",
  },
];

export enum ShipSizes {
  SMALL,
  MEDIUM,
  LARGE,
}

export const ships: Ship[] = [
  {
    name: "Belbullab-22 Starfighter",
    icon: "[",
    factions: [Factions.SEPARATIST_ALLIANCE],
    dimensions: {
      size: ShipSizes.SMALL,
      height: 14,
      width: 22,
      length: 33,
    },
    panels: {
      primary: {
        factionIconSize: 5,
        shipIconSize: 21
      },
      sides: {
        factionIconSize: 4,
        shipIconSize: 7,
        leftOffset: -7,
      },
      top: {
        factionIconSize: 4,
        shipIconSize: 4
      }
    }
  },
  {
    name: "Droid Tri-Fighter",
    icon: "+",
    factions: [Factions.SEPARATIST_ALLIANCE],
    dimensions: {
      size: ShipSizes.SMALL,
      height: 21,
      width: 19,
      length: 29,
    },
    panels: {
      primary: {
        factionIconSize: 5,
        shipIconSize: 19
      },
      sides: {
        factionIconSize: 4,
        shipIconSize: 16,
        leftOffset: 0,
        rightOffset: 2
      },
      top: {
        factionIconSize: 4,
        shipIconSize: 13
      }
    }
  },
  // {
  //   name: "HMP Droid Gunship",
  //   icon: ".",
  //   size: ShipSizes.SMALL,
  //   height: 13,
  //   width: 43,
  //   length: 55,
  //   sideLeftOffset: -4.5,
  //   displayFactionSize: 5,
  //   displayIconSize: 46,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 7,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 5,
  //   factions: [Factions.SEPARATIST_ALLIANCE],
  // },
  // {
  //   name: "Hyena-Class Droid Bomber",
  //   icon: "=",
  //   size: ShipSizes.SMALL,
  //   height: 13,
  //   width: 33,
  //   length: 47,
  //   sideLeftOffset: -8.5,
  //   displayFactionSize: 5,
  //   displayIconSize: 38,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 7,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 5,
  //   factions: [Factions.SEPARATIST_ALLIANCE],
  // },
  // {
  //   name: "Nantex-Class Starfighter",
  //   icon: ";",
  //   size: ShipSizes.SMALL,
  //   height: 10,
  //   width: 20,
  //   length: 42,
  //   displayTop: false,
  //   displaySide: false,
  //   displayFactionSize: 5,
  //   displayIconSize: 29,
  //   factions: [Factions.SEPARATIST_ALLIANCE],
  // },
  // {
  //   name: "Vulture-class Droid Fighter",
  //   icon: "_",
  //   size: ShipSizes.SMALL,
  //   height: 16,
  //   width: 24,
  //   length: 34,
  //   sideLeftOffset: -7,
  //   displayFactionSize: 5,
  //   displayIconSize: 22,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 9,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 5,
  //   factions: [Factions.SEPARATIST_ALLIANCE],
  // },
  // {
  //   name: "TIE Interceptor",
  //   icon: "I",
  //   size: ShipSizes.SMALL,
  //   height: 25,
  //   width: 32,
  //   length: 40,
  //   sideLeftOffset: 3,
  //   displayFactionSize: 5,
  //   displayIconSize: 28,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 16,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 15,
  //   factions: [Factions.GALACTIC_EMPIRE],
  // },
  // {
  //   name: "TIE/D Defender",
  //   icon: "D",
  //   size: ShipSizes.SMALL,
  //   height: 42,
  //   width: 42,
  //   length: 38,
  //   sideLeftOffset: 10,
  //   displayFactionSize: 5,
  //   displayIconSize: 26,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 28,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 32,
  //   factions: [Factions.GALACTIC_EMPIRE],
  // },
  {
    name: "RZ-1 A-Wing",
    icon: "a",
    factions: [Factions.REBEL_ALLIANCE],
    dimensions: {
      size: ShipSizes.SMALL,
      height: 15,
      width: 27,
      length: 39,
    },
    panels: {
      top: {
        factionIconSize: 4,
        shipIconSize: 4,
      },
      primary: {
        factionIconSize: 5,
        shipIconSize: 27,
      },
      sides: {
        factionIconSize: 4,
        shipIconSize: 6,
        leftOffset: 1, // 0
        rightOffset: 2, // 0
      }
    }
    // height: 15,
    // width: 27,
    // length: 39,
    // sideLeftOffset: 1, // 0
    // sideRightOffset: 2, // 0
    // displayFactionSize: 5,
    // displayIconSize: 27,
    // displaySideFactionSize: 4,
    // displaySideIconSize: 6,
    // displayTopFactionSize: 4,
    // displayTopIconSize: 4,
  },
  // {
  //   name: "A/SF-01 B-Wing",
  //   modifier: "(Folding Wings)",
  //   icon: "b",
  //   size: ShipSizes.SMALL,
  //   height: 15,
  //   width: 32,
  //   length: 65,
  //   sideLeftOffset: 0, // -3
  //   sideRightOffset: 1, // 5
  //   displayFactionSize: 5,
  //   displayIconSize: 52,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 6,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 4,
  //   factions: [Factions.REBEL_ALLIANCE],
  // },
  // {
  //   name: "HWK-290 Light Freighter",
  //   icon: "h",
  //   size: ShipSizes.SMALL,
  //   height: 18,
  //   width: 52,
  //   length: 66,
  //   sideLeftOffset: -8,
  //   sideRightOffset: -3,
  //   displayFactionSize: 5,
  //   displayIconSize: 54,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 15,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 12,
  //   factions: [Factions.REBEL_ALLIANCE, Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "BTL-A4 Y-Wing",
  //   modifier: "(2.0 Sculpt)",
  //   icon: "y",
  //   size: ShipSizes.SMALL,
  //   height: 17,
  //   width: 33,
  //   length: 63,
  //   sideLeftOffset: 0, // -1
  //   sideRightOffset: 3, // 0
  //   displayFactionSize: 5,
  //   displayIconSize: 47,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 9,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 7,
  //   factions: [Factions.REBEL_ALLIANCE, Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "TIE/rb Heavy",
  //   icon: "J",
  //   size: ShipSizes.MEDIUM,
  //   height: 42,
  //   width: 62,
  //   length: 56,
  //   sideLeftOffset: 5,
  //   sideRightOffset: 12,
  //   displayFactionSize: 5,
  //   displayIconSize: 47,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 40,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 35,
  //   factions: [Factions.GALACTIC_EMPIRE],
  // },
  // {
  //   name: "Aggressor Assault Fighter",
  //   icon: "i",
  //   size: ShipSizes.MEDIUM,
  //   height: 19,
  //   width: 60,
  //   length: 77,
  //   sideLeftOffset: -6,
  //   sideRightOffset: -4,
  //   displayFactionSize: 5,
  //   displayIconSize: 67,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 12,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 12,
  //   factions: [Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "Kihraxz Fighter",
  //   icon: "r",
  //   size: ShipSizes.SMALL,
  //   height: 13,
  //   width: 38,
  //   length: 46,
  //   sideLeftOffset: -3,
  //   sideRightOffset: -1,
  //   displayFactionSize: 5,
  //   displayIconSize: 36,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 6,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 7,
  //   factions: [Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "BTL-A4 Y-Wing",
  //   modifier: "(1.0 Sculpt)",
  //   icon: "y",
  //   size: ShipSizes.SMALL,
  //   height: 14,
  //   width: 32,
  //   length: 63,
  //   sideLeftOffset: -1, // -2
  //   sideRightOffset: 1, // -1
  //   displayFactionSize: 5,
  //   displayIconSize: 47,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 9,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 7,
  //   factions: [Factions.REBEL_ALLIANCE, Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "M3-A Interceptor",
  //   icon: "s",
  //   size: ShipSizes.SMALL,
  //   height: 13,
  //   width: 33,
  //   length: 37,
  //   sideLeftOffset: -5, // -2
  //   sideRightOffset: -2, // 0
  //   displayFactionSize: 5,
  //   displayIconSize: 27,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 9,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 7,
  //   factions: [Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "Scurrg H-6 Bomber",
  //   icon: "H",
  //   size: ShipSizes.SMALL,
  //   height: 21,
  //   width: 52,
  //   length: 77,
  //   sideLeftOffset: -2, // -3
  //   sideRightOffset: 1, // -1
  //   displayFactionSize: 5,
  //   displayIconSize: 40,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 16,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 12,
  //   factions: [Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "StarViper-class Attack Platform",
  //   icon: "v",
  //   size: ShipSizes.SMALL,
  //   height: 27,
  //   width: 39,
  //   length: 69,
  //   sideLeftOffset: -6,
  //   sideRightOffset: -3,
  //   displayFactionSize: 5,
  //   displayIconSize: 58,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 19,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 17,
  //   factions: [Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "Quadrijet Transfer Spacetug",
  //   icon: "q",
  //   size: ShipSizes.SMALL,
  //   height: 26,
  //   width: 49,
  //   length: 40,
  //   sideLeftOffset: -4,
  //   sideRightOffset: -2,
  //   displayFactionSize: 5,
  //   displayIconSize: 30,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 19,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 18,
  //   factions: [Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "Mining Guild TIE Fighter",
  //   icon: "C",
  //   size: ShipSizes.SMALL,
  //   height: 28,
  //   width: 36,
  //   length: 43,
  //   sideLeftOffset: -1,
  //   sideRightOffset: 3,
  //   displayFactionSize: 5,
  //   displayIconSize: 33,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 23,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 17,
  //   factions: [Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "M12-L Kimogila Fighter",
  //   icon: "K",
  //   size: ShipSizes.MEDIUM,
  //   height: 23,
  //   width: 58,
  //   length: 55,
  //   sideLeftOffset: -1,
  //   displayFactionSize: 5,
  //   displayIconSize: 47,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 9,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 7,
  //   factions: [Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "Fang Fighter",
  //   modifier: "(1.0 Sculpt)",
  //   icon: "M",
  //   size: ShipSizes.SMALL,
  //   height: 15,
  //   width: 44,
  //   length: 46,
  //   sideLeftOffset: 0,
  //   sideRightOffset: 1,
  //   displayFactionSize: 5,
  //   displayIconSize: 37,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 9,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 7,
  //   factions: [Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "G-1A Starfighter",
  //   icon: "n",
  //   size: ShipSizes.SMALL,
  //   height: 35,
  //   width: 44,
  //   length: 68,
  //   sideLeftOffset: 6,
  //   sideRightOffset: 9,
  //   displayFactionSize: 5,
  //   displayIconSize: 57,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 29,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 26,
  //   factions: [Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "Z-95-AF4 Headhunter",
  //   icon: "z",
  //   size: ShipSizes.SMALL,
  //   height: 16,
  //   width: 35,
  //   length: 46,
  //   sideLeftOffset: -5,
  //   displayFactionSize: 5,
  //   displayIconSize: 37,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 9,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 7,
  //   factions: [Factions.REBEL_ALLIANCE, Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "TIE Advanced x1",
  //   icon: "A",
  //   size: ShipSizes.SMALL,
  //   height: 21,
  //   width: 34,
  //   length: 32,
  //   sideLeftOffset: 0,
  //   sideRightOffset: 3,
  //   displayFactionSize: 5,
  //   displayIconSize: 23,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 18,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 12,
  //   factions: [Factions.GALACTIC_EMPIRE],
  // },
  // {
  //   name: "TIE Advanced v1",
  //   icon: "R",
  //   size: ShipSizes.SMALL,
  //   height: 19,
  //   width: 34,
  //   length: 31,
  //   sideLeftOffset: 1,
  //   displayFactionSize: 5,
  //   displayIconSize: 20,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 11,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 10,
  //   factions: [Factions.GALACTIC_EMPIRE],
  // },
  // {
  //   name: "TIE/sk Striker",
  //   icon: "T",
  //   size: ShipSizes.SMALL,
  //   height: 18,
  //   width: 38,
  //   length: 64,
  //   sideLeftOffset: 0,
  //   sideRightOffset: 2,
  //   displayFactionSize: 5,
  //   displayIconSize: 26,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 12,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 10,
  //   factions: [Factions.GALACTIC_EMPIRE],
  // },
  // {
  //   name: "TIE/ag Aggressor",
  //   icon: "`",
  //   size: ShipSizes.SMALL,
  //   height: 24,
  //   width: 32,
  //   length: 35,
  //   sideLeftOffset: 2,
  //   displayFactionSize: 5,
  //   displayIconSize: 25,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 16,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 15,
  //   factions: [Factions.GALACTIC_EMPIRE],
  // },
  // {
  //   name: "TIE/ph Phantom",
  //   icon: "P",
  //   size: ShipSizes.SMALL,
  //   height: 25,
  //   width: 30,
  //   length: 43,
  //   sideLeftOffset: 1,
  //   sideRightOffset: 5,
  //   displayFactionSize: 5,
  //   displayIconSize: 26,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 22,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 12,
  //   factions: [Factions.GALACTIC_EMPIRE],
  // },
  // {
  //   name: "TIE/ln Fighter",
  //   icon: "F",
  //   size: ShipSizes.SMALL,
  //   height: 34,
  //   width: 36,
  //   length: 44,
  //   sideLeftOffset: 7, // 8
  //   sideRightOffset: 12, // 10
  //   displayFactionSize: 5,
  //   displayIconSize: 26,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 28,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 22,
  //   factions: [Factions.GALACTIC_EMPIRE, Factions.REBEL_ALLIANCE],
  // },
  // {
  //   name: "TIE/sa Bomber",
  //   icon: "B",
  //   size: ShipSizes.SMALL,
  //   height: 24,
  //   width: 45,
  //   length: 40,
  //   sideLeftOffset: 3,
  //   displayFactionSize: 5,
  //   displayIconSize: 26,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 16,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 16,
  //   factions: [Factions.GALACTIC_EMPIRE],
  // },
  // {
  //   name: "TIE/ca Punisher",
  //   icon: "N",
  //   size: ShipSizes.MEDIUM,
  //   height: 30,
  //   width: 56,
  //   length: 47,
  //   sideLeftOffset: 3,
  //   sideRightOffset: 10,
  //   displayFactionSize: 5,
  //   displayIconSize: 26,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 28,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 22,
  //   factions: [Factions.GALACTIC_EMPIRE],
  // },
  // {
  //   name: "TIE Reaper",
  //   icon: "V",
  //   size: ShipSizes.MEDIUM,
  //   height: 22,
  //   width: 56,
  //   length: 90,
  //   sideLeftOffset: 5,
  //   displayFactionSize: 5,
  //   displayIconSize: 76,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 10,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 12,
  //   factions: [Factions.GALACTIC_EMPIRE],
  // },
  // {
  //   name: "Alpha-class Star Wing",
  //   icon: "&",
  //   size: ShipSizes.SMALL,
  //   height: 34,
  //   width: 36,
  //   length: 65,
  //   sideLeftOffset: 3,
  //   sideRightOffset: 6,
  //   displayFactionSize: 5,
  //   displayIconSize: 26,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 28,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 32,
  //   factions: [Factions.GALACTIC_EMPIRE],
  // },
  // {
  //   name: "A/SF-01 B-Wing",
  //   modifier: "(Fixed Wings)",
  //   icon: "b",
  //   size: ShipSizes.SMALL,
  //   height: 32,
  //   width: 38,
  //   length: 58,
  //   sideLeftOffset: 7, // 5
  //   sideRightOffset: 11, // 9
  //   displayFactionSize: 5,
  //   displayIconSize: 52,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 28,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 24,
  //   factions: [Factions.REBEL_ALLIANCE],
  // },
  // {
  //   name: "T-65 X-Wing",
  //   modifier: "(Fixed Wings)",
  //   icon: "x",
  //   size: ShipSizes.SMALL,
  //   height: 18,
  //   width: 41,
  //   length: 49,
  //   sideLeftOffset: 0,
  //   sideRightOffset: 4,
  //   displayFactionSize: 5,
  //   displayIconSize: 40,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 14,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 4,
  //   factions: [Factions.REBEL_ALLIANCE],
  // },
  // {
  //   name: "T-65 X-Wing",
  //   modifier: "(Folding Wings)",
  //   icon: "x",
  //   size: ShipSizes.SMALL,
  //   height: 14,
  //   width: 40,
  //   length: 49,
  //   sideLeftOffset: 0,
  //   sideRightOffset: 0, // 2
  //   displayFactionSize: 5,
  //   displayIconSize: 40,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 6,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 4,
  //   factions: [Factions.REBEL_ALLIANCE],
  // },
  // {
  //   name: "ARC-170 Starfighter",
  //   icon: "c",
  //   size: ShipSizes.MEDIUM,
  //   height: 21,
  //   width: 54,
  //   length: 83,
  //   sideLeftOffset: -3,
  //   sideRightOffset: 1,
  //   displayFactionSize: 5,
  //   displayIconSize: 52,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 18,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 13,
  //   factions: [Factions.REBEL_ALLIANCE, Factions.GALACTIC_REPUBLIC],
  // },
  // {
  //   name: "Attack Shuttle",
  //   icon: "g",
  //   size: ShipSizes.SMALL,
  //   height: 18,
  //   width: 29,
  //   length: 46,
  //   sideLeftOffset: -1,
  //   sideRightOffset: 1,
  //   displayFactionSize: 5,
  //   displayIconSize: 37,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 13,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 10,
  //   factions: [Factions.REBEL_ALLIANCE],
  // },
  // {
  //   name: "Auzituck Gunship",
  //   icon: "@",
  //   size: ShipSizes.SMALL,
  //   height: 25,
  //   width: 32,
  //   length: 57,
  //   sideLeftOffset: 2,
  //   sideRightOffset: 4,
  //   displayFactionSize: 5,
  //   displayIconSize: 37,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 20,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 17,
  //   factions: [Factions.REBEL_ALLIANCE],
  // },
  // {
  //   name: "UT-60D U-Wing",
  //   icon: "u",
  //   size: ShipSizes.MEDIUM,
  //   height: 23,
  //   width: 35,
  //   length: 91,
  //   sideLeftOffset: 3,
  //   displayFactionSize: 5,
  //   displayIconSize: 42,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 16,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 14,
  //   factions: [Factions.REBEL_ALLIANCE],
  // },
  // {
  //   name: "Sheathipede-class Shuttle",
  //   icon: "%",
  //   size: ShipSizes.SMALL,
  //   height: 20,
  //   width: 24,
  //   length: 43,
  //   sideLeftOffset: -4,
  //   sideRightOffset: -4,
  //   displayFactionSize: 5,
  //   displayIconSize: 31,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 10,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 4,
  //   factions: [Factions.REBEL_ALLIANCE, Factions.SEPARATIST_ALLIANCE],
  // },
  // {
  //   name: "TIE/FO Fighter",
  //   icon: "O",
  //   size: ShipSizes.SMALL,
  //   height: 33,
  //   width: 35,
  //   length: 39,
  //   sideLeftOffset: 8,
  //   displayFactionSize: 5,
  //   displayIconSize: 28,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 26,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 22,
  //   factions: [Factions.FIRST_ORDER],
  // },
  // {
  //   name: "TIE/SF Fighter",
  //   icon: "S",
  //   size: ShipSizes.SMALL,
  //   height: 33,
  //   width: 35,
  //   length: 39,
  //   sideLeftOffset: 8,
  //   displayFactionSize: 5,
  //   displayIconSize: 29,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 26,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 24,
  //   factions: [Factions.FIRST_ORDER],
  // },
  // {
  //   name: "TIE/vn Silencer",
  //   icon: "$",
  //   size: ShipSizes.SMALL,
  //   height: 24,
  //   width: 43,
  //   length: 80,
  //   sideLeftOffset: 3,
  //   displayFactionSize: 5,
  //   displayIconSize: 58,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 16,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 16,
  //   factions: [Factions.FIRST_ORDER],
  // },
  // {
  //   name: "TIE/Ba Interceptor",
  //   icon: "j",
  //   size: ShipSizes.SMALL,
  //   height: 26,
  //   width: 34,
  //   length: 41,
  //   sideLeftOffset: 0,
  //   sideRightOffset: 4,
  //   displayFactionSize: 5,
  //   displayIconSize: 32,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 22,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 18,
  //   factions: [Factions.FIRST_ORDER],
  // },
  // {
  //   name: "Xi-class Light Shuttle",
  //   icon: "Q",
  //   size: ShipSizes.MEDIUM,
  //   height: 43,
  //   width: 74,
  //   length: 65,
  //   sideLeftOffset: 5,
  //   sideRightOffset: 10,
  //   displayFactionSize: 5,
  //   displayIconSize: 52,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 35,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 34,
  //   factions: [Factions.FIRST_ORDER],
  // },
  // {
  //   name: "Delta-7 Aethersprite",
  //   icon: "\\",
  //   size: ShipSizes.SMALL,
  //   height: 14,
  //   width: 26,
  //   length: 36,
  //   sideLeftOffset: -6,
  //   sideRightOffset: -4,
  //   displayFactionSize: 5,
  //   displayIconSize: 30,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 9,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 8,
  //   factions: [Factions.GALACTIC_REPUBLIC],
  // },
  // {
  //   name: "Naboo Royal N-1 Starfighter",
  //   icon: "<",
  //   size: ShipSizes.SMALL,
  //   height: 14,
  //   width: 30,
  //   length: 53,
  //   sideLeftOffset: -10,
  //   sideRightOffset: -8,
  //   displayFactionSize: 5,
  //   displayIconSize: 38,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 8,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 4,
  //   factions: [Factions.GALACTIC_REPUBLIC],
  // },
  // {
  //   name: "Syliure-class Hyperspace Ring",
  //   icon: "*",
  //   size: ShipSizes.SMALL,
  //   height: 22,
  //   width: 38,
  //   length: 43,
  //   sideLeftOffset: -7,
  //   sideRightOffset: -5,
  //   displayFactionSize: 5,
  //   displayIconSize: 34,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 16,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 14,
  //   factions: [Factions.GALACTIC_REPUBLIC],
  // },
  // {
  //   name: "Eta-2 Actis",
  //   modifier: "in Syliure-class Hyperspace Ring",
  //   icon: "-*",
  //   size: ShipSizes.SMALL,
  //   height: 25,
  //   width: 38,
  //   length: 36,
  //   sideLeftOffset: 0,
  //   sideRightOffset: 2,
  //   displayFactionSize: 5,
  //   displayIconSize: 21,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 16,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 19,
  //   factions: [Factions.GALACTIC_REPUBLIC],
  // },
  // {
  //   name: "Eta-2 Actis",
  //   icon: "-",
  //   size: ShipSizes.SMALL,
  //   height: 15,
  //   width: 24,
  //   length: 27,
  //   sideLeftOffset: 0,
  //   displayFactionSize: 5,
  //   displayIconSize: 18,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 8,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 7,
  //   factions: [Factions.GALACTIC_REPUBLIC],
  // },
  // {
  //   name: "V-19 Torrent",
  //   icon: "^",
  //   size: ShipSizes.SMALL,
  //   height: 27,
  //   width: 32,
  //   length: 58,
  //   sideLeftOffset: 6,
  //   displayFactionSize: 5,
  //   displayIconSize: 48,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 16,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 18,
  //   factions: [Factions.GALACTIC_REPUBLIC],
  // },
  // {
  //   name: "BTL-B Y-Wing",
  //   icon: ":",
  //   size: ShipSizes.SMALL,
  //   height: 16,
  //   width: 34,
  //   length: 72,
  //   sideLeftOffset: 0,
  //   displayFactionSize: 5,
  //   displayIconSize: 52,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 6,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 4,
  //   factions: [Factions.GALACTIC_REPUBLIC],
  // },
  // {
  //   name: "LAAT/i Gunship",
  //   icon: "/",
  //   size: ShipSizes.SMALL,
  //   height: 34,
  //   width: 62,
  //   length: 64,
  //   sideLeftOffset: 6,
  //   displayFactionSize: 5,
  //   displayIconSize: 50,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 20,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 22,
  //   factions: [Factions.GALACTIC_REPUBLIC],
  // },
  // {
  //   name: "Fireball",
  //   icon: "0",
  //   size: ShipSizes.SMALL,
  //   height: 16,
  //   width: 50,
  //   length: 49,
  //   sideLeftOffset: 3,
  //   displayFactionSize: 5,
  //   displayIconSize: 38,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 6,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 7,
  //   factions: [Factions.RESISTANCE],
  // },
  // {
  //   name: "T-70 X-Wing",
  //   modifier: "(Fixed Wings)",
  //   icon: "w",
  //   size: ShipSizes.SMALL,
  //   height: 17,
  //   width: 44,
  //   length: 48,
  //   sideLeftOffset: 0,
  //   sideRightOffset: 2,
  //   displayFactionSize: 5,
  //   displayIconSize: 37,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 10,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 7,
  //   factions: [Factions.RESISTANCE],
  // },
  // {
  //   name: "T-70 X-Wing",
  //   modifier: "(Folding Wings)",
  //   icon: "w",
  //   size: ShipSizes.SMALL,
  //   height: 15,
  //   width: 44,
  //   length: 48,
  //   sideLeftOffset: 0,
  //   sideRightOffset: 1,
  //   displayFactionSize: 5,
  //   displayIconSize: 37,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 8,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 4,
  //   factions: [Factions.RESISTANCE],
  // },
  // {
  //   name: "RZ-2 A-Wing",
  //   icon: "E",
  //   size: ShipSizes.SMALL,
  //   height: 16,
  //   width: 23,
  //   length: 38,
  //   sideLeftOffset: 0,
  //   sideRightOffset: 2,
  //   displayFactionSize: 5,
  //   displayIconSize: 28,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 9,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 8,
  //   factions: [Factions.RESISTANCE],
  // },
  // {
  //   name: "Resistance Transport",
  //   icon: ">",
  //   size: ShipSizes.SMALL,
  //   height: 23,
  //   width: 37,
  //   length: 68,
  //   sideLeftOffset: -3,
  //   sideRightOffset: 2,
  //   displayFactionSize: 5,
  //   displayIconSize: 38,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 20,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 12,
  //   factions: [Factions.RESISTANCE],
  // },
  // {
  //   name: "Resistance Transport Pod",
  //   icon: "?",
  //   size: ShipSizes.SMALL,
  //   height: 14,
  //   width: 21,
  //   length: 23,
  //   displaySide: false,
  //   displayFactionSize: 4,
  //   displayIconSize: 12,
  //   displaySideFactionSize: 2,
  //   displaySideIconSize: 20,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 0,
  //   factions: [Factions.RESISTANCE],
  // },
  // {
  //   name: "Lancer-Class Pursuit Craft",
  //   icon: "L",
  //   height: 34,
  //   width: 120,
  //   length: 122,
  //   size: ShipSizes.LARGE,
  //   displayFactionSize: 4,
  //   displayIconSize: 82,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 20,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 20,
  //   factions: [Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "YT-2400",
  //   icon: "o",
  //   height: 34,
  //   width: 68,
  //   length: 102,
  //   size: ShipSizes.LARGE,
  //   displayFactionSize: 4,
  //   displayIconSize: 60,
  //   displaySideFactionSize: 2,
  //   displaySideIconSize: 25,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 25,
  //   factions: [Factions.REBEL_ALLIANCE],
  // },
  // {
  //   name: "VT-49 Decimator",
  //   icon: "d",
  //   height: 37,
  //   width: 97,
  //   length: 143,
  //   size: ShipSizes.LARGE,
  //   displayFactionSize: 4,
  //   displayIconSize: 52,
  //   displaySideFactionSize: 2,
  //   displaySideIconSize: 20,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 15,
  //   factions: [Factions.GALACTIC_EMPIRE],
  // },
  // {
  //   name: "B/SF-17 Bomber",
  //   icon: "Z",
  //   height: 58,
  //   width: 81,
  //   length: 112,
  //   size: ShipSizes.LARGE,
  //   displayFactionSize: 4,
  //   displayIconSize: 70,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 30,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 15,
  //   factions: [Factions.RESISTANCE],
  // },
  // {
  //   name: "Upsilon-Class Shuttle",
  //   icon: "U",
  //   height: 53,
  //   width: 134,
  //   length: 65,
  //   size: ShipSizes.LARGE,
  //   displayFactionSize: 4,
  //   displayIconSize: 56,
  //   displaySideFactionSize: 2,
  //   displaySideIconSize: 20,
  //   displayTopFactionSize: 6,
  //   displayTopIconSize: 40,
  //   factions: [Factions.FIRST_ORDER],
  // },
  // {
  //   name: "Customized YT-1300 Light Freighter",
  //   icon: "W",
  //   height: 30,
  //   width: 148,
  //   length: 100,
  //   size: ShipSizes.LARGE,
  //   displayFactionSize: 4,
  //   displayIconSize: 82,
  //   displaySideFactionSize: 2,
  //   displaySideIconSize: 20,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 18,
  //   factions: [Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "Lambda-Class T-4A Shuttle",
  //   icon: "l",
  //   height: 46,
  //   width: 70,
  //   length: 75,
  //   size: ShipSizes.LARGE,
  //   displayFactionSize: 4,
  //   displayIconSize: 62,
  //   displaySideFactionSize: 2,
  //   displaySideIconSize: 20,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 35,
  //   factions: [Factions.GALACTIC_EMPIRE],
  // },
  // {
  //   name: "Jumpmaster 5000",
  //   icon: "p",
  //   height: 24,
  //   width: 80,
  //   length: 77,
  //   size: ShipSizes.LARGE,
  //   displayFactionSize: 4,
  //   displayIconSize: 65,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 20,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 10,
  //   factions: [Factions.SCUM_AND_VILLAINY],
  // },
  // {
  //   name: "Modified YT-1300 Freighter",
  //   icon: "m",
  //   height: 34,
  //   width: 98,
  //   length: 126,
  //   size: ShipSizes.LARGE,
  //   displayFactionSize: 4,
  //   displayIconSize: 90,
  //   displaySideFactionSize: 2,
  //   displaySideIconSize: 20,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 25,
  //   factions: [Factions.REBEL_ALLIANCE],
  // },
  // {
  //   name: "Scavenged YT-1300 Freighter",
  //   icon: "Y",
  //   height: 34,
  //   width: 98,
  //   length: 126,
  //   size: ShipSizes.LARGE,
  //   displayFactionSize: 4,
  //   displayIconSize: 90,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 20,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 25,
  //   factions: [Factions.RESISTANCE],
  // },
  // {
  //   name: "BTA-NR2 Y-Wing",
  //   icon: "{",
  //   height: 17,
  //   width: 35,
  //   length: 69,
  //   size: ShipSizes.SMALL,
  //   sideLeftOffset: -3,
  //   sideRightOffset: 0,
  //   displayFactionSize: 5,
  //   displayIconSize: 38,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 12,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 10,
  //   factions: [Factions.RESISTANCE],
  // },
  // {
  //   name: "TIE/se Bomber",
  //   icon: "!",
  //   height: 24,
  //   width: 63,
  //   length: 65,
  //   // orientation: "side",
  //   size: ShipSizes.SMALL,
  //   sideLeftOffset: 2,
  //   sideRightOffset: 0,
  //   displayFactionSize: 5,
  //   displayIconSize: 52,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 15,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 18,
  //   factions: [Factions.FIRST_ORDER],
  // },
  // {
  //   name: "TIE/wi Whisper Modified Interceptor",
  //   icon: "#",
  //   height: 23,
  //   width: 34,
  //   length: 75,
  //   size: ShipSizes.SMALL,
  //   sideLeftOffset: -11,
  //   sideRightOffset: -7,
  //   displayFactionSize: 5,
  //   displayIconSize: 49,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 20,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 12,
  //   factions: [Factions.FIRST_ORDER],
  // },
  // {
  //   name: "Nimbus-class V-Wing",
  //   icon: ",",
  //   height: 19,
  //   width: 33,
  //   length: 28,
  //   size: ShipSizes.SMALL,
  //   sideLeftOffset: -3,
  //   sideRightOffset: 2,
  //   displayFactionSize: 5,
  //   displayIconSize: 18,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 16,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 12,
  //   factions: [Factions.GALACTIC_REPUBLIC],
  // },
  // {
  //   name: "VCX-100 Light Freighter",
  //   icon: "G",
  //   height: 55,
  //   width: 155,
  //   length: 120,
  //   size: ShipSizes.LARGE,
  //   sideLeftOffset: -3,
  //   sideRightOffset: 2,
  //   displayFactionSize: 5,
  //   displayIconSize: 108,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 42,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 42,
  //   factions: [Factions.REBEL_ALLIANCE],
  // },
  // {
  //   name: "Firespray-class Patrol Craft",
  //   icon: "f",
  //   height: 35,
  //   width: 78,
  //   length: 78,
  //   // orientation: "side",
  //   size: ShipSizes.MEDIUM,
  //   sideLeftOffset: -3,
  //   sideRightOffset: 2,
  //   displayFactionSize: 5,
  //   displayIconSize: 69,
  //   displaySideFactionSize: 4,
  //   displaySideIconSize: 25,
  //   displayTopFactionSize: 4,
  //   displayTopIconSize: 25,
  //   factions: [Factions.SCUM_AND_VILLAINY, Factions.SEPARATIST_ALLIANCE],
  // },
];